#ifndef SHARED_BITFLAGS_H
#define SHARED_BITFLAGS_H

#define RRC_BITFLAGS_SAVEGAME (1 << 0)
#define RRC_BITFLAGS_LOADED_FROM_RR (1 << 1) // set by pulsar
#define RRC_BITFLAGS_RR_CRASHED (1 << 2)     // set by pulsar
#define RRC_BITFLAGS_MY_STUFF_CTGP (1 << 3)
#define RRC_BITFLAGS_MY_STUFF_RR (1 << 4)
#define RRC_BITFLAGS_MY_STUFF_CTGP_MUSIC (1 << 5)
#define RRC_BITFLAGS_MY_STUFF_RR_MUSIC (1 << 6)
#define RRC_BITFLAGS_MY_STUFF_ANY (RRC_BITFLAGS_MY_STUFF_CTGP | RRC_BITFLAGS_MY_STUFF_RR | RRC_BITFLAGS_MY_STUFF_CTGP_MUSIC | RRC_BITFLAGS_MY_STUFF_RR_MUSIC)
#define RRC_BITFLAGS_MY_STUFF_ANY_MUSIC (RRC_BITFLAGS_MY_STUFF_CTGP_MUSIC | RRC_BITFLAGS_MY_STUFF_RR_MUSIC)

#endif
